version: "3"

services:
  caddy:
    image: caddy:2.4.6-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    links:
      - php

  php:
    build: .
    volumes:
      - ./:/var/www/html